# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=0.1.0-milestone1
maven_group=com.aicivilization
archives_base_name=aicivilization

# Dependencies
fabric_api_version=0.161.0+26.2
polymer_version=0.17.5+26.2
